# cargo-about: the third-party license file shipped in release archives
# (THIRD_PARTY_LICENSES.md). Same allowlist as deny.toml.
accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
